# UNAUTHORIZED ACCESS TO THIS PLAYBOOK IS PROHIBITED
# You must have explicit, authorized permission to access or configure this playbook. 
# Unauthorized attempts and actions to access or use this may result in civil and/or criminal penalties. 
# All activities performed on this are logged and monitored.

# CIANDT Ansible Playbook: Sites Configuration
# Author: Pillar Squad

# Look for devices inside "proxyserver" tag
- hosts: proxyserver
  become: yes
  become_user: root

  vars: 
  - name: conffilename
    private: no
    unsafe: no

  - name: site
    private: no
    unsafe: no

  - name: proxy_rewrite_destination
    private: no
    unsafe: no

# Look for "sites_configuration" role
  roles:
    - sites_configuration