# UNAUTHORIZED ACCESS TO THIS PLAYBOOK IS PROHIBITED
# You must have explicit, authorized permission to access or configure this playbook. 
# Unauthorized attempts and actions to access or use this may result in civil and/or criminal penalties. 
# All activities performed on this are logged and monitored.

# CIANDT Ansible Task from Snowpack playbook
# Author: marioc@ciandt.com

  - name: Install python-setuptools
    package:
      name: python3-setuptools
      state: present

  - name: install python-pip
    package:
      name: python3-pip
      state: present

  - name: Install boto3 and botocore with pip3 module
    pip:
      name: 
      - boto3
      - botocore
      executable: pip-3.6

  - name: Execute Snow scan 
    shell: /opt/snow/snowagent scan
  
  - name: Copy file to S3 bucket
    vars:
      ansible_python_interpreter: /usr/bin/python3
    community.aws.s3_sync: 
      aws_access_key: '{{ aws_access_key }}' 
      aws_secret_key: '{{ aws_secret_key }}'
      bucket: 'ciandt-pillars-squad' 
      file_root: /opt/snow/data/
      include: "*snowpack"
