---
- name: Update Octopus Tentacles
  hosts: "{{target|default('localhost')}}"
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_port: 5986
    ansible_winrm_scheme: https
  tasks:
    - name: Set download directory
      ansible.builtin.set_fact:
        agent_dl_dir: "{{ drives.data }}:\tools"
        octopus_dir: "{{ drives.data }}:\Octopus"

    - name: Create tools directory
      ansible.windows.win_file:
        path: "{{ agent_dl_dir }}"
        state: directory

    - name: Create octopus directory
      ansible.windows.win_file:
        path: "{{ octopus_dir }}"
        state: directory

    - name: Download octopus tentacle msi
      ansible.windows.win_shell: |
        gsutil cp {{ agents.octopus.tentacle_gcs_uri }} {{ agent_dl_dir }}\\OctopusTentacle-{{ agents.octopus.tentacle_version }}.msi
      args:
        creates: "{{ agent_dl_dir }}\\OctopusTentacle-{{ agents.octopus.tentacle_version }}.msi"
        chdir: C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin

    - name: Stop OctopusDeploy Polling Tentacle
      ansible.windows.win_service:
        name: "OctopusDeploy Tentacle: Polling"
        state: stopped

    - name: Install octopus from msi
      ansible.windows.win_package:
        path: "{{ agent_dl_dir }}\\OctopusTentacle-{{ agents.octopus.tentacle_version }}.msi"
        arguments: "/qn /norestart"

    - name: Start OctopusDeploy Polling Tentacle
      ansible.windows.win_service:
        name: "OctopusDeploy Tentacle: Polling"
        state: started