linux:
  hosts:
    ansible-linux-host:
      ansible_user: jroberts_jackhenry_com
      ansible_host: 34.136.232.254

windows:
  hosts:
    devdb:
      ansible_user: jroberts
      ansible_host: 34.123.103.182
      ansible_connection: winrm
      ansible_winrm_transport: kerberos
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_port: 5986
      ansible_winrm_scheme: https
