- name: Set EnableCertPaddingCheck registry values
  ansible.windows.win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
  loop:
    - { path: 'HKLM:\Software\Microsoft\Cryptography\Wintrust\Config', name: 'EnableCertPaddingCheck', type: 'string', data: "1" }
    - { path: 'HKLM:\Software\Wow6432Node\Microsoft\Cryptography\Wintrust\Config', name: 'EnableCertPaddingCheck', type: 'string', data: "1" }