- name: Install latest PowerShell
  ansible.windows.win_powershell:
    script: |
      $latest_msi_uri = (gcloud storage ls {{ repository }}/patching/PowerShell*.msi | Sort-Object -Descending | Select-Object -First 1)     
      $msi_filename = ($latest_msi_uri.Split("/") | Select-Object -Last 1)
      $version = $msi_filename.Split("-")[1]

      $app = Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -match "PowerShell" }

      if ($app.Version -lt "$($version)") {
        gsutil cp $($latest_msi_uri) D:
        Start-Process C:\Windows\System32\msiexec.exe -ArgumentList "/i D:\$($msi_filename) /passive /norestart" -wait
        Remove-Item D:\$($msi_filename)
        Start-Process C:\Windows\System32\msiexec.exe -ArgumentList "/x $($app.IdentifyingNumber) /passive /norestart" -wait
      }