# UNAUTHORIZED ACCESS TO THIS PLAYBOOK IS PROHIBITED
# You must have explicit, authorized permission to access or configure this playbook. 
# Unauthorized attempts and actions to access or use this may result in civil and/or criminal penalties. 
# All activities performed on this are logged and monitored.

# CIANDT Ansible Handlers from Linux Server Hardening playbook
# Author: marioc@ciandt.com

- name: "restart ntp"
  service:
    name: ntp
    state: restarted

- name: "restart snmpd"
  service:
    name: snmpd
    state: restarted
  
- name: "restart sshd"
  service:
    name: snmpd
    state: restarted