collections:
  - name: ansible.posix
    version: ">=1.5.4"
    source: https://galaxy.ansible.com
  - name: ansible.windows
    version: ">=2.2.0"
    source: https://galaxy.ansible.com
  - name: community.general
    version: ">=7.3.0"
    source: https://galaxy.ansible.com
  - name: community.windows
    version: ">=1.13.0"
    source: https://galaxy.ansible.com
  - name: community.crypto
    version: ">=2.15.0"
    source: https://galaxy.ansible.com
  - name: google.cloud
    version: ">=1.2.0"
    source: https://galaxy.ansible.com
  - name: microsoft.ad
    version: ">=1.3.0"
    source: https://galaxy.ansible.com
